### ISSUE TITLE
After clearing the history, the extension completely stops tracking the clipboard

### ISSUE THREAD

**Issue by rsilvr** [oae/gnome-shell-pano#318]
## Description

After I click the 'Clear History' menu of the extension, any other content I try to copy stops showing up in Pano. A workaround for this issue is to disable and then re-enable the extension, after which functionality is restored.

### Problem Explanation

After I click the "Clear History" menu of the extension I can't copy anything to Pano until I restarted it.

### Expected Behavior

If I click the "Clear History" menu, all my past copied content should be wiped out, but new content should still be copied as normal. Instead, in addition to clearing the history, the extension is not copying anything else (similar to the behavior of "Incognito Mode").

### Steps To Reproduce

Steps to reproduce, if applicable:

1. Copy some content
2. Click the "Clear History" menu in Pano
3. Copy more stuff
4. Open Pano and check that nothing copied in step 3 was saved.

#### It happens with any application?

- [X] Yes, it applies to any application.

#### It happens only on one computer?

- [X] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [X] I don't think that the configuration matters.

#### It happens only with some specific extension installed?

- [X] I don't think that the installed extensions affect the bug/behavior.

### Environment

- GNOME Shell version: 46
- Distro: Ubuntu 
- Distro version: 24.04.1 LTS

#### Gnome

``` bash
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
out 06 12:50:52 ubuntu-note gnome-shell[86394]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
out 06 12:51:02 ubuntu-note gnome-shell[86394]: [pano] [database] connection is not opened
out 06 12:51:11 ubuntu-note gnome-shell[86394]: [pano] [database] connection is not opened
out 06 12:51:17 ubuntu-note gnome-shell[86394]: [pano] [database] connection is not opened
out 06 12:51:18 ubuntu-note gnome-shell[86394]: [pano] [database] connection is not opened
out 06 12:51:23 ubuntu-note gnome-shell[86394]: [pano] [database] connection is not opened
```

#### Pano Configuration

```bash
[/]
history-length=100
is-in-incognito=false
paste-on-select=false
play-audio-on-copy=false
send-notification-on-copy=false
session-only-mode=true
sync-primary=false
wiggle-indicator=false
```

#### Enabled Extensions

```bash
['ding@rastersoft.com',
'ubuntu-dock@ubuntu.com',
'tiling-assistant@ubuntu.com',
'auto-move-windows@gnome-shell-extensions.gcampax.github.com',
'do-not-disturb-while-screen-sharing-or-recording@marcinjahn.com',
'mediacontrols@cliffniff.github.com',
'quick-settings-audio-panel@rayzeq.github.io',
'status-area-horizontal-spacing@mathematical.coffee.gmail.com',
'Vitals@CoreCoding.com',
'order-extensions@wa4557.github.com',
'windowIsReady_Remover@nunofarruca@gmail.com',
'workrave@workrave.org',
'lilypad@shendrew.github.io',
'PrivacyMenu@stuarthayhurst',
'pano@elhan.io']
```
